import type { PlaybookBase } from "../types";

export const CrownsPearl: PlaybookBase = {
	title: "The Crown's Pearl",
	intro: [
		"The Denizens of the Deep were many, and ruling over them all was the Pearl Court. Once upon a time, you were its scion. You enjoyed a charmed childhood, darting through the kelp forests and coral fortresses of your future kingdom. But then you met the landwalkers. Everyone knows the story. Yours was a fairytale romance; a union between the kingdoms of sea and sky. By your joining, the lands above and seas below would enjoy everlasting peace and prosperity… but the songs don’t mention what it cost you. The pain, the subjugation… the things that were demanded of you. When you could take no more, you reminded them that merfolk have teeth. Your feral children spread across the land, devouring and despoiling everything in their path. They ate your subjects, they ate your spouse, and they set fire and ruin to everything else. The survivors called it war, but to you it was just nature.",

		"You awoke in the ruins of what was once yours. When you returned to the Kingdom Beneath the Waves, you found the forests withered and warped, the coral bleached, and the only denizens left were stunted abominations—monstrous things, lacking the fluked tails of your people, gurgling prayers to new gods. You, Ember, are the last of the Pearl Court; you will journey to the Old Capital, even though you have no legs upon which to walk. You represent the hope, perhaps, that the seas may one day thrive again. Or maybe you’ll drag everything down to it instead.",
	],
	names: [
		"Aliké",
		"Astell",
		"Cerimis",
		"Cirilha",
		"Deoré",
		"Èchis",
		"Euonité",
		"Harmonia",
		"Haylith",
		"Hel",
		"Kellec",
		"Kylitea",
		"Myress",
		"Orésis",
		"Pétra",
		"Phrenyx",
		"Rhené",
		"Selania",
		"Trillea",
		"Zerusa",
	],
	honorifics: [
		" With Lips of Coral",
		"With Scales of Sapphire",
		"With Fins of Flashing Silver",
		"With the Voice of Dawn",
		"the Jewel of the Deep",
		"the Strength of Storms",
		"the Wave Dancer",
		"the Shimmering",
		"the Ruby-Eyed",
		"the Abyssal Star",
		"the Cherished",
		"the Thundersong",
		"the Salt-Crowned",
		"the Lightning-Born",
		"the Nelumbo’s Kiss",
		"the Dirge of Dusk",
		"the Shark-Charmer",
		"the Gift of the Tides",
		"the Crystalline Lily",
		"the Scintillant Sovereign",
	],
	look: [
		"A bleached coral hairpiece",
		"a rigid head crest where hair should be",
		"finned ears with bioluminescent tips",
		"kelp woven through your hair",
		"slitted pupils over glittering sclera",
		"large, bulging fish eyes",
		"sapphire teardrop earrings",
		"needle-sharp teeth",
		"a necklace of shark teeth",
		"iridescent scale patterns across your skin",
		"webbed fingers, too long to be mistaken as human",
		"the smell of sea spray and salt",
		"gill slits along your lowest ribs",
		"ancillary fins along your forearms and lower body",
		"ornamental strings of pearls and seashells",
		"a repurposed fishing net worn as a garment",
		"a whalebone corset with the bones exposed",
		"a rich silken dress, tattered and weathered from the waist down",
		"squid ink tattoos scrawled across your body",
		"a scar from an old harpoon wound",
	],
	rituals: [
		"Deep Murmurings",
		"Sand Scrawlings",
		"Stoking the Cold Flame",
		"Kelp Weaving",
		"The Hymn of Salt and Sorrow",
	],
	questions: [
		"Did the Embers resolve a Mystery?",
		"Did you roll with Cinder?",
		"Did you show us the beauty in your monstrosity?",
		"Did you go out of your way to indulge your curiosity towards something from landwalker culture?",
		"Did you allow a landwalker to indulge their curiosity towards you?",
		"Did you lament the loss of the world before the Dimning, openly or internally?",
		"Did you invoke your royalty to dismiss someone beneath you?",
	],
	abilities: {
		vitality: 1,
		composure: 1,
		reason: 0,
		presence: 1,
		cinder: -2,
	},
	cinders: {
		1: "The Rising Tide — All will be devoured, in time.",
		2: "Storms — Nothing survives the lash of wind and rain forever.",
		3: "Lights — Beacons to guide the lost, or lure the unwary.",
		4: "The Fathomless Depths — Mysteries abound where light cannot dwell",
		5: "Fury — Fire is not the only thing that burns.",
	},
	relics: [
		{
			title: "The Coral Horn",
			text: "A spiraling horn of coral in the likeness of a spiked conch shell, azure merfolk runes etched in its surface. When sounded in or near the water, it summons a kelpie, appearing like a charcoal black horse with kelp tangled in its mane. <aspect>It has the strength of ten horses</aspect>. Your kelpie can carry you anywhere so long as it remains in view of a body of water, but <aspect>it will drown anyone else who attempts to ride it</aspect>. Having carried you in your wedding procession, <aspect>it knows the difference between a regret and a mistake</aspect>.",
			extraLines: 2,
		},
		{
			title: "The Gem of Drowned Flame",
			text: "A brilliant sphere of blue encapsulating what looks like <aspect>a frozen explosion, perhaps a shard of the Old Flame itself</aspect>. Worn as a necklace, but can be set in a tiara. Those who accept an invitation to stare into it are <aspect>lulled into a pleasant waking sleep, amenable to suggestion</aspect>. It is said to be <aspect>the key to a sunken vault of merfolk treasure</aspect>.",
			extraLines: 2,
		},
		{
			title: "The Sea Witch’s Quiver",
			text: "<aspect>A quiver containing arrows fletched by fish fins instead of feathers</aspect>. <aspect>They fly true, even when fired underwater</aspect>. The arrows stored in this quiver are anointed with sea urchin oil that can <aspect>petrify the dead or poison the living</aspect>.",
			extraLines: 2,
		},
	],
	oldFire: [
		"Narrate a flashback to the time when you first glimpsed wonders from the world above the waves. What did you keep for yourself?",
		"Narrate a flashback to the time you first saw the landwalker royal scion who would eventually become your spouse. Name them. What about them made you instantly fall in love with them? What evidence of their cruelty did you miss?",
		"Narrate a flashback to your wedding. Despite the joy around you, what about the occasion shows us that you were more of a prisoner than a spouse?",
		"Narrate a flashback to a time that your spouse demanded you sacrifice something important and irreplaceable, to prove your love to them.",
		"Describe a vignette of when the Sea Witch Casylda of the Abyss foresaw the Dimning, and what terrible fate befell her when she witnessed such ruin.",
		"Narrate a flashback to the time when you watched your children, feral and monstrous, devour your spouse’s kingdom. Did you welcome this ruin, or did you do everything in your power to stop it?",
		"Describe what form the Dimning took. What were your last thoughts as you witnessed the terrible vengeance that the survivors of your children’s wave of terror turned against you and the Court Beneath the Waves?",
	],
	fireToCome: {
		"The Kindling Gate":
			"Pick a Cinder (do not mark it if it is unmarked) and cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate.",
		"The Tinder Arch":
			"Tell the story of the Leviathan. What were they before the Dimning, and why will they not rest until you specifically are destroyed? Take the Condition: Marked by the Leviathan; the Condition cannot be cleared in the normal ways.",
		"The Hearth’s Fuel":
			"A group of horrible, warped aquatic gaunts come across something from the Pearl Court, half-buried in the sand. What do they discover that once belonged to you? Narrate a scene of their religious attachment to the object. If mergaunt are present in a Mystery, they will present you with a task. So long as you do what they want, they will not be a Danger for you.",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1.",
		"The Pyre’s Crown":
			"Narrate the moment you turn from the company and walk alone toward the Throne at the heart of the Old Capital. Then, at the end of this play session, read Ascend the Throne.",
	},
	ascendTheThrone: [
		"The skies darkened before you even appeared on the black marble steps of the Old Capital. Now, the clouds, pregnant with thunder and grumbling impatiently, blanket the skies such that no stars can witness your ascent, nor can the moons voice their protest. Finding the throne room is no challenge; blue fire sconces guide the way through the labyrinthine halls. Perhaps they recognize your royalty. Or perhaps all castles are to some degree the same to you.",

		"And there it sits before you: a silly old chair, with its silly little legs. As if in coronation, the sky begins to release a vanguard of fat droplets, the first pummeling of rain that will lash these stones for weeks, and into months, until naught a statue or fresco remains above the waterline. The lapping tides will gorge themselves on this falling sea, until this Old Kingdom finally joins with yours beneath the waves.",

		"<strong>Narrate what will happen should you drown the Throne of the Old King.</strong>",

		"Do you take command of the stunted and monstrous things in the deep, forging an Undersea Empire to wage war against any who cling to dry land? Do you begin the laborious process of rebuilding the Kingdom Beneath the Waves, reef by strangled reef? Or do you eventually pull the tides back, swallowing the sins of the old world into the darkness of the abyss to let the landwalkers begin again, on beaches as fresh as a new dawn?",
	],
	moves: [
		{
			title: "…I Will Be Thy Muse…",
			text: [
				"Your grace and poise are recorded in the tales of the Old Kingdom. When another Ember would mark The Fire to Come in your presence, they may instead mark this move and describe what about you inspires them to boldly seize the moment. When the final box is marked, mark XP and cross out this move.",
			],
			checkboxes: [false, false, false],
		},
		{
			title: "…I Will Come When I Am Called…",
			text: [
				"When you mark someone in the style of the merfolk, say how you intend to do so. If it is a Side Character, roll the Light Move based on your appeal. If you intend to mark a fellow Ember, they simply have to accept it, but they take the mark as a Condition. Once a person is so marked, you can always hear them when they call your name.",
			],
		},
		{
			title: "…I Will Find Thy Foes…",
			text: [
				"When you swim aimlessly through the water in the proximity of an active Mystery, unshackling your mind from all worldly concerns and letting it drift through the expanse, roll with Cinder. On a hit, you come across an enemy, or evidence of an enemy’s passing. You may ask the Keeper two of the following:",
				"How has humanity treated them? The Keeper will answer in the form of a Clue.",
				"What do they want from _______? The Keeper will answer in the form of a Clue.",
				"What are they afraid of? You gain advantage on an associated roll if you use this information against them.",
				"Have they been chained, physically or metaphorically? If the Keeper says no, ask a different question. If the Keeper says yes, and you take the time to unburden them, physically or symbolically, you may mark one box beneath “My Word is My Vow.” If you have already regained your voice, you may unmark an Aspect of the Song of Storm and Silver.",
				"On a 7-9, the Keeper may place you or a Side Character in peril, or ask something of you in return.",
			],
		},
		{
			title: "…I Will Walk Thy Lands In Triumph and Tumult.”",
			text: [
				"The Sea Witch Casylda taught you a ritual to temporarily replace your tail fluke with human legs. When you are unobserved and you enact your ritual, roll Cinder. On a hit, you become passably human for a time; you grow hair if you had none, your fins and scales retract, your pupils change shape, but most importantly, you may walk on two feet as landwalkers do. Additionally, choose one benefit. On a 10+, choose two:",
				"Your Presence increases by 1 (Max 4) while the magic lasts.",
				"You will stumble across a Clue; the Keeper will tell you what it is.",
				"Your form is considered quite charming. Someone will do a small task for you.",
				"You will learn something about an upcoming trouble or obstacle; roll with advantage the first time you act on this information.",
				"Then, choose one drawback:",
				"The spell fades before you want it to.",
				"It is incredibly painful: take the Condition Walking on Knives.",
				"A nearby Danger is drawn by the use of magic.",
				"On a 12+, if you are Mute, you may mark one box on “My Word is My Vow…”. If you have already regained your voice, you may unmark an Aspect of the Song of Storm and Silver.",
			],
		},
	],
};
