import type { PlaybookBase } from "../types";

export const CruxDruid: PlaybookBase = {
	title: "The Crux Druid",
	intro: [
		"You were one of the crux druids—reviled wanderers, feared mystics, and keepers of the most terrible rites. While others knelt before the Old Fire, you knelt before root and bark and stone, listening for the whispered truths that seeped through the marrow of the earth. But the land only speaks when fed, and your order learned early that blood loosens every tongue.",

		"You crucified the willing and the condemned alike upon sacred trees. Their gasping pleas, their half-mad mutterings, their final shuddering breaths—all were threads in the tapestry of knowledge your order wove. You buried hearts in riverbeds to coax storms. You spilled blood on barren soil to wake slumbering spirits. You carved sigils into living bone and pressed them into the loam to twist nature to your purpose. The kingdoms despised you. The churches cursed you. The Fae would not speak your name. But the land… the land listened.",

		"When the Dimning came and the world reeled, you did not despair. You welcomed the Great Unmaking, for in the darkness, the land’s true voice rose raw and unbound, whispering secrets no one else dared hear.",

		"Now you rise again, an improbable tool of the Old Fire. The trees remember your touch—some with reverence, some with hunger. And everywhere you walk, the world strains to speak once more…",
	],
	names: [
		"Mavren",
		"Ilyra",
		"Wynreth",
		"Brisca",
		"Saeven",
		"Quorra",
		"Hareth",
		"Nyselle",
		"Calyxe",
		"Urelle",
		"Aelith",
		"Thryza",
		"Pellis",
		"Faelis",
		"Dymra",
		"Vaelis",
		"Oritha",
		"Kessune",
		"Eirwen",
		"Liorra",
	],
	honorifics: [
		"Who Listens Beneath the Bark",
		"of the Cruciform Grove",
		"Who Drinks the Root’s Murmur",
		"of Hanging Bough and Bleeding Earth",
		"Who Reads the Gallows-Tree",
		"of Blood-Soaked Loam",
		"Who Hears the Soil’s Confession",
		"Who Feeds the Land Its Due",
		"of the Red Canopy",
		"Who Knows the Weight of Sap and Sorrow",
		"of the Verdant Crucible",
		"Who Walks Where Trees Remember",
		"of the Green Scaffold",
		"of Root and Rib",
		"of the Hanging Orchard",
		"Who Hung the Living Psalm",
		"Who Pressed Ear to Earth",
		"Who Counted the Rings of Suffering",
		"of the Greer Gallows",
		"of the Crooked Trunk",
	],
	look: [
		"hair braided with dried thorns and prayer-knots",
		"scalp shaved clean except for ritual scars etched in black sap ink",
		"tangled hair matted with leaves and old blood",
		"a crown of nailed twigs pressed into the brow",
		"eyes stained green from sap or bile",
		"lips split and re-stitched with bark cord",
		"chest marked with cruciform scars",
		"a bark-wrapped cuirass bound with iron staples",
		"a robe of layered leaves stiffened with dried gore",
		"ribs cinched with a leather harness bearing hanging charms of teeth and nails",
		"a corded belt strung with finger bones and river stones",
		"a satchel reeking of loam, packed with untoward things wrapped in linen",
		"forearms banded in living vines that tighten when blood is spilled",
		"hands blackened with resin and old sap burns",
		"fingers capped with thorn rings used for carving flesh",
		"a skirt of hide panels flayed from sacrificial beasts",
		"legstains dark from blood running down",
		"calves wrapped in vines knotted tight",
		"bare feet hardened and split like roots",
		"heavy boots studded with rusted nails and packed with soil from sacred groves",
	],
	rituals: [
		"The Red Silence",
		"The Root-Counting",
		"The Long Thirst of the Earth",
		"The Testament of Splinters",
		"The Burial of Eyes",
	],
	questions: [
		"Did you perform a rite others found abhorrent, frightening, or unforgivable?",
		"Did you demonstrate reverence for root, stone, or soil over law, crown, or creed?",
		"Did you spill blood in a way that caused the land to respond?",
		"Did you give cold comfort to the suffering?",
		"Did you give a wild-eyed monologue about how the land is speaking to you even now?",
	],
	abilities: {
		vitality: 0,
		reason: 0,
		presence: 1,
		composure: 2,
		cinder: -2,
	},
	cinders: {
		1: "The Speaking Root — The land reveals truth only when fed suffering.",
		2: "The Cruciform Grove — Pain, properly placed, sanctifies the world.",
		3: "The Open Vein — Blood is the shortest path between will and nature.",
		4: "The Welcome Dark — The Dimning was not an ending, but a clearing.",
		5: "Iron & Twig — Nature does not endure by softness alone.",
	},
	relics: [
		{
			title: "Harrow the Martyr-Catcher",
			text: "An <aspect>iron sickle attached to a long chain</aspect>. A weapon from the ancient world, it is thought to contain <aspect>the life force of the first crux druid, Harrow the Martyr-Catcher</aspect>. Some say it does its dark work independent of the desires of its wielder, and <aspect>can only be satisfied if the whole world hangs</aspect>.",
			extraLines: 2,
		},
		{
			title: "The Heartwood Nails",
			text: "A bundle of <aspect>iron spikes</aspect>, each forged with a vein of heartwood: <aspect>ash for healing and rebirth</aspect>, <aspect>blackthorn for dispelling magic</aspect>, <aspect>silver birch for punishment</aspect>, and <aspect>yew to purify the dead</aspect>.",
			extraLines: 2,
		},
		{
			title: "The Tenderbark Confessor",
			text: "Sometimes called the Rib-Rake, this is <aspect>a long staff twisted with vines and flowers</aspect>, nails roughly hammered along its length. It ends in <aspect>a claw of sharpened branches and iron splints</aspect>, used to peel skin and muscle from bone. They say its “tenderbark embrace” is <aspect>the most exquisite pain known to man or beast</aspect>.",
			extraLines: 2,
		},
	],
	oldFire: [
		"Narrate a flashback to your initiation as a crux druid, when you first heard the land speak clearly through suffering. Who was bound to the tree, and what small mercy did you grant them before the rite began?",
		"Narrate a flashback to the first time you were named a monster. Who witnessed your work and fled in horror, and what part of their terror did you quietly understand, even as you refused to stop?",
		"Narrate a flashback to when priests, lords, or Fae attempted to destroy you and your order. Who among them spoke to you as if you were still a person, and why did their words linger with you longer than any curse?",
		"Narrate a flashback to the height of your infamy, when your name alone could empty villages. What miracle did you force from the land through crucifixion, and who did you spare—against doctrine—because you could not bear to hear their voice on the tree?",
		"Narrate a flashback to the moment you realized the Dimning was coming. What changed in the voices of root, stone, and bone?",
		"Narrate a flashback to the Dimning’s arrival, when others screamed and begged the Old Fire for mercy. Who did you try to warn, and what did it cost you to watch them die?",
		"Narrate a flashback to the final rite you performed before the Great Unmaking. Who was crucified, what prophecy did you receive, and what doubt—small but indelible—did you carry with you into the end?",
	],
	fireToCome: {
		"The Kindling Gate":
			"Pick a Cinder (do not mark it if it is unmarked) and cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate.",
		"The Tinder Arch": "Mark 3 Stigma.",
		"The Hearth's Fuel": "Unmark 1 Stigma.",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1.",
		"The Pyre's Crown":
			"Narrate the moment you turn from the company and walk alone toward the Throne at the heart of the Old Capital. Then, at the end of this play session, read Ascend the Throne",
	},
	ascendTheThrone: [
		"You carry the grafted ash sapling into the Old Capital. The tree is heavy with blood, bone, and memory. The halls resist you—stone cracks, iron weeps rust, the obsidian dead turn their faces away—but the land beneath the city listens. The Throne of the Old King waits, split and hollow, a wound where rule once sat.",

		"You place the sapling in the Throne’s hollow. Roots immediately stir, threading into marble and gold as if they were loam. The Throne groans and yields. Branches spread where crowns once hovered. Pillars split. The ceiling vanishes into leaf and shadow. Over time, the Capital becomes a forested nave, and the voices you fed to the land rise—not in screams, but in chorus.",
		"There will be no more kings.",
		"<strong>Narrate what will happen should you reach the Throne, and the world is ruled by the Tree’s fire.</strong> ",
		"Does the Tree speak, and if so, with what voice, and how do the people learn to listen? If it does not speak, how do the people make their way in this new verdant tyranny? How do they avoid falling again into madness and despair? ",
		"After a time, the Tree is large enough for you to make one last sacrifice to it.",
		"<strong>Narrate the moment when you crucify yourself to the Tree.</strong> ",
		"What part of you does the Tree treasure most? What part of you does it resent? What mercy, if any, does it learn from you?",
	],
	moves: [
		{
			title: "Give My Death Meaning…",
			text: [
				"It seems the world is full of unwilling sacrifices—martyrs who must have their sacred role revealed through violence. ",

				"You can name humanoid Dangers and Servants as part of <strong>“Do Not Let Me Hang Alone…”</strong>; they are always unwilling martyrs (as if you had rolled 7-9), and the subsequent Dark Move is taken at disadvantage. Making a Servant an Oracle permanently lowers your Cinder by 1 (no min), but you can take body parts for <strong>“…Plant Me Where My Power Can Grow”</strong> at a cost of just 1 box marked, and their eventual death is a Lord Clue. ",
			],
		},
		{
			title: "…Carve Your Commands on My Bones…",
			text: [
				"You are talented at the rare art of bone casting—the carving of runes on living bone to create wells of mystical power you can tap into from anywhere. ",
				"While on a Journey that has an Oracle, you can narrate a scene showing how you peel the flesh from—and then carve a rune on—one of the Oracle’s bones. If you do so, say what the rune does and then write it on the Journey sheet (with its own checkbox) beneath the Oracle; it acts as an Aspect, even after the Oracle is dead. ",
			],
		},
		{
			title: "…Give the Land Claim to My Body…",
			text: [
				"You can make quick sacrifices to the land in order to command nature: a heart submerged in a river can cause a wall of water to crash into your foes, a piece of bone planted in the ground can summon the wind, a pair of eyes set on a tree branch can reveal a safe path, and much more besides. ",
				"If you have time to bury or ritually place a body part from “...Plant Me Where My Power Can Grow”, you can harness the power of nature to automatically overcome a Danger; clear the body part from the list and describe what it looks like when nature intervenes on your behalf. ",
			],
		},
		{
			title: "…And Let the World Remember Me When I’m Gone.",
			text: [
				"You form a psychic bond with all your living Oracles when facing a powerful foe, and can sacrifice them instantly, drawing on the surge of power created by their deaths to summon nature to your side. ",
				"During a Struggle, you can avoid a single die roll by marking all the remaining boxes on an Oracle and describing how the power of the sacrifice causes nature to intervene on your behalf. You can also re-direct questions posed to other Embers in the Struggle to you for this purpose. You can use this move as many times as you wish during a Struggle so long as there are living Oracles to sacrifice. ",
			],
		},
	],
};
