import type { PlaybookBase } from "../types";

export const FallenSkynight: PlaybookBase = {
	title: "The Fallen Skynight",
	intro: [
		"You soared across the endless blue skies on the back of one of the world’s great airbeasts, aiding the needy at times of peace, and reporting on enemy positions in times of war. Then came the Dimning, and you, like the other Embers, fell. The wyverns and griffons and greathawks, all the great airbeasts, vanished or went feral. When you awoke, you found yourself, in odd company: a Great Lord was gathering strength, and you, listless and forsaken, clung to their power for a time. They had promised what no one else could: a path back to the azure expanse that was taken from you—a clutch of juvenile airbeasts like the one you once rode.",
		"You never learned the full extent of the Lord’s plans, but you learned enough to cut ties, and so you stole away with a fledgling just as it began to imprint on you. Now inseparable, the two of you made your way through the perilous mists and valleys, until you finally found yourself here, in the company of these other Embers. However, you were not the Lord’s only Skyknight-aspirant. They had in their company one other, who still wishes to see their plans come to fruition. They are now your Rival. They will do whatever it takes to bring you back into the fold.",
		"You still yearn to return to the skies. This fledgling is your greatest hope. But better still would be to find the Throne of the Hidden King; perhaps then, a new age could see its dawn, and as you know, dawn is the best time to take flight.",
	],
	names: [
		"Straea",
		"Beleze",
		"Altenora",
		"Pallax",
		"Torono",
		"Valestra",
		"Revel",
		"Orsen",
		"Nalor",
		"Krace",
		"Jenneth",
		"Siga",
		"Ariado",
		"Firon",
		"Shyri",
		"Tessel",
		"Tevesh",
		"Kyro",
		"Doritea",
		"Salenina",
	],
	honorifics: [
		"Skydancer",
		"Highcloud",
		"Thunderheart",
		"Swiftwing",
		"Redwind",
		"Mooncrest",
		"Starcaller",
		"Silversong",
		"Stormswallow",
		"Mourningfeather",
		"the Ghost of Vyrag",
		"the Baron Ablaze",
		"the Stormtamer",
		"the Rose of Dawn",
		"the Maiden of Marcuria",
		"the Star of Fury",
		"the Pale Shrike",
		"the Dragonslayer",
		"the Moons’ Chosen",
		"the Rising Sun",
	],
	look: [
		"sallet tasseled with the plumes of a now-extinct pheasant",
		"wild hair, too heavy with dirt to be stirred by the wind",
		"an impressively long but fraying braid",
		"goggles on your forehead, one lens cracked",
		"eyes hidden behind a beastmaw visor you refuse to lift",
		"moisture trails from the charcoal streak across your eyes and nose",
		"dull eyes, the color of the unpleasant clouds",
		"lopsided smirk that once shined with confidence",
		"long, dusty scarf whipping in the wind",
		"feather scale shoulderguards creaking against itself",
		"billowing cape, colors faded from sun exposure",
		"tarnished medallions, some of them yours",
		"loose straps dangling from a full-body riding harness",
		"lightweight brass armor, needing polishing",
		"one arm armored more than the other",
		"scorched fur along the trim of your bracers and breastplate",
		"loose ends hanging from linen hand wraps",
		"dusty white tiger skin wrapped around your waist",
		"hip satchel that once held small tools and animal treats",
		"long, tattered fabric train, barely hanging on",
	],
	rituals: [
		"Measuring the Wind",
		"Parapet Vigil",
		"Skysongs",
		"The Step of Seven Bells",
		"The Azure Trance",
	],
	questions: [
		"Did you leap boldly into combat against a bigger, tougher, or stronger foe?",
		"Did you hide your true emotions from someone?",
		"Did you find something that gives you hope the natural world will recover from the Dimning?",
		"Did you share a treasured memory of flight?",
		"Did you mourn the airbeast you once rode?",
	],
	abilities: {
		vitality: 1,
		composure: 1,
		reason: 1,
		presence: 0,
		cinder: -2,
	},
	cinders: {
		1: "The Endless Sky — So long as there is blue above, mankind will dream.",
		2: "The Roaring Winds — That which does not bend, breaks.",
		3: "The Wild Lightning — Danger and thrill live less than a breath apart.",
		4: "The Twilight’s Banner — There is a deep beauty in the way things end.",
		5: "The Falling Star — The oddest fortunes occur when the tapestry of heavens is cut.",
	},
	relics: [
		{
			title: "Green Gale",
			type: "relic",
			text: "A legendary <aspect>ranseur made of a unique skymetal alloy</aspect>, exceptionally strong for its light weight. Its bearer can <aspect>command the wind with a gesture</aspect>. Those who carry it are said to <aspect>dream of soaring flight</aspect>, <aspect>unburdened by the weight of doubt</aspect>.",
			extraLines: 3,
		},
		{
			title: "Skystride Sabatons",
			type: "relic",
			text: "<aspect>Articulated armor for the foot, shin, and calf</aspect>, with short heels for stirrups. Legends tell of skyknights able to mount and dismount their flying beasts mid-flight, <aspect>leaping impossible heights and landing unharmed from any altitude</aspect>. They are even said to be able to <aspect>balance perfectly, even on surfaces no larger than a sword’s tip</aspect>.",
			extraLines: 3,
		},
		{
			title: "The Fledgling",
			type: "relic",
			text: "A juvenile airbeast, roughly the size of a large housecat, though it will be much larger someday. For now, it can <aspect>glide short distances and carry small objects</aspect>, but mostly it takes long naps and chirrups when hungry, which is often. Despite the fearsome mien of its older kin, many find its current childlike curiosity and budding intelligence <aspect>quite adorable</aspect>.",
			extraLines: 4,
		},
	],
	oldFire: [
		"Narrate a flashback to your first fateful encounter with an airbeast, and how it set you on the path to become a skyknight.",
		"Narrate a flashback to the time you first alighted on the back of your airbeast as a pairbonded mount and rider.",
		"Narrate a flashback to your greatest aerial triumph. What happened, that the bards still tell tales about?",
		"Narrate a flashback to the incident that made you wonder if you’d ever fly again, and what got you through those dark days.",
		"Narrate a flashback to the time you gave love a chance, and how your skyknight duties made that path difficult.",
		"Describe the omen, vision, or horror that appeared in the skies, heralding the Dimning to come. Where were you, and why didn’t you warn those who could perhaps have taken action?",
		"Narrate a flashback to your final fall, that one that finally took your life.",
	],
	fireToCome: {
		"The Kindling Gate":
			"Pick a Cinder and cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate.",
		"The Tinder Arch":
			"At some point in the near future, the Keeper will inform you that the Fledgling has been kidnapped, by your Rival or some other Danger. You lose access to the Fledgling until you answer the following Question: Where was the Fledgling taken? (Complexity: 2). Opportunity: Locate and rescue the Fledgling. Any Mystery’s Clues may be used to answer this Question.",
		"The Hearth's Fuel":
			"The Lord’s magic has advanced the growth of your Rival’s airbeast. Describe how, now fully-grown, it is visibly corrupted and even more terrifying than normal.",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1.",
		"The Pyre's Crown":
			"Narrate the moment you turn from the company and walk alone toward the Throne at the heart of the Old Capital. Then, at the end of this play session,read Ascend the Throne.",
	},
	ascendTheThrone: [
		"Your fledgling is now too large to perch on your shoulders, or be carried in the crook of your arm as it once did; so now it walks beside you along the paths of broken stone. The twisting, darkened streets of the Old Capitol do everything in their power to confound and dishearten you. But there is one route available to you that even the city does not anticipate: the avenue above. It is that untrodden path, across the rooftops and among the tattered banners, unfurling in a new breeze as though waking from a long slumber, that you find your way to the throne room, entering from above.",
		"There, beside the Throne, is your Rival. They make one last, desperate plea for you to turn back. But their hand is on their weapon. All it would take is a single strike, and the Throne could be yours. Or perhaps there is a different way?",
		"<strong>Narrate what will happen should you ascend the Throne of the Hidden King.</strong>",
		"Do you guard the Throne, living quietly off this land until the fledgling is big enough to carry the both of you away from this miserable place, to see what lies beyond the western skies, where the Bright Star sleeps?",
		"Or do you stay a little longer, developing the keep into a peerless aerie for your airbeast, and all its children and cousins, growing and seeking bigger prey for them to feed on, until the roaring chorus can no longer be contained, thus beginning the Age of Monsters?",
		"And what happened to your Rival, in the end?",
	],
	moves: [
		{
			title: "…Nor In the Skies Around Them…",
			text: [
				"When you call the sky’s lightning to you and let it flow through Green Gale, mark a box below and take your next roll with advantage. If another move or effect already gives you advantage, take the roll with double advantage (roll four dice and keep the two highest, or turn disadvantage into advantage).",
				"When the final box is marked, the stored lightning lashes out from your body. Unmark all boxes and roll with Cinder. On a 7-9, choose one. On a 10+, choose two:",
				"<li>Your lightning discharges safely, and does not strike anyone nearby.</li>",
				"<li>The power coursing through you gives you uncanny insight in the form of a Clue—tell the Keeper what it is.</li>",
				"<li>You discharge everything; if you do not choose this option, take the Condition: Overcharged and lose access to this move until it is cleared.</li>",
				"On a miss, your Ember is consumed entirely by overwhelming power. Describe it, then retire this character.",
			],
			checkboxes: 3,
		},
		{
			title: "…Nor the Beasts Below Them…",
			text: [
				"You can communicate with animals, either directly or in a manner of gesture and intuition that passes as speech. When you commune with a local beast, roll with Presence if it is smaller than you, or Composure if it is larger. On a hit, choose one from below. On a 10+, choose two:",
				"<li>The animal, through words, wisdom, or actions, clears an Aspect.</li>",
				"<li>The animal reveals a Clue; tell the Keeper what it is. The Clue cannot conclusively answer a Question by itself.</li>",
				"<li>The animal makes a request of you. When you complete it, mark XP.</li>",
				"<li>The animal shares its knowledge about a nearby Danger. The first time you act on this information, roll with advantage.</li>",
				"On a miss, mark a box on your Rival’s track.",
			],
		},
		{
			title: "…Nor In Monsters Great and Terrible…",
			text: [
				"You may mark a known Danger as your primary target. When you do, name your quarry, and take the Condition: On the Hunt. If you are already On the Hunt, stoke the Fire. Until that Danger is destroyed or otherwise ceases to be a threat, and so long as you have the On the Hunt Condition, you roll with advantage when attempting to locate, capture, or defeat it, but you make all other rolls at disadvantage. While you have a target marked in this manner, you always find an additional Clue on the Information Move whenever directly inquiring about the target, even on a miss.",
			],
		},
		{
			title: "…Not Even In Their Peers.",
			text: [
				"Perhaps your aloof exterior encourages further exploration, or maybe it’s just the note in your voice. Whatever it is, people find your spark oddly magnetic. Add 1 to your Presence (max 3), but cross off a box from your Rival’s track; that box can no longer be marked. Roll with advantage when acting to throw someone off guard, discourage unwanted attention, or de-escalate a situation through patience and diplomacy. When you take this move, narrate a flashback to a time when you and the Rival trained in combat together. Who got the better of the other, and how?",
			],
		},
	],
};
