import type { PlaybookBase } from "../types";

export const HallowedHeart: PlaybookBase = {
	title: "The Hallowed Heart",
	intro: [
		"Heroes need something to fight for and so they fought for you. The court that raised you fed you hopes for a better world, clad you in golden silks soft to the touch, kept you wide-eyed and innocent. To place a kiss upon your hand, the humblest farmer could find a knight’s valor. To hear their name fall from your lips, knights would march into death without blinking. ",

		"Even the Dimning could not sour your sweetness. Your heart broke for the world, and in your breaking you reached out. The people flocked to you, united in the exalted purpose of loving you. One stood out above all others: your Champion, who devoted their life to protecting you. ",

		"The Dimning took them all: your followers, who fell wide-eyed and weeping with joy for knowing that their death meant your life. Your Champion. Even you, in what you thought was your final sacrifice.",

		"Now you rise once more, once more the broken yearn for your love. You long to forgive the sickness at the heart of it all: The Dimning itself. To make it all the way to the Hidden Throne, you will have to accept an imperfect Champion, and do what you do best: hope.",
	],
	names: [
		"Anmir",
		"Aelin",
		"Aurelia",
		"Bellan",
		"Branwyn",
		"Cyrion",
		"Calla",
		"Elyon",
		"Esthar",
		"Mylana",
		"Melic",
		"Kaerdin",
		"Iseul",
		"Iolas",
		"Lores",
		"Ygrain",
		"Noradin",
		"Lyonesse",
		"Sauda",
		"Morwenna",
	],
	honorifics: [
		"The Gentle",
		"The Once and Future",
		"The All-Loving",
		"Who Dreams Through The Noise",
		"Who Walks in Hope",
		"Of the Chrysalis Court",
		"Sun-Crowned",
		"The Tenderhearted",
		"With Wings of Gold",
		"Who Brings Forth The Dawn",
		"The Sweet Mercy",
		"The Bright-Eyed",
		"The Undimmed Radiance",
		"Soothed in Sorrow",
		"of the Everblooming Spring",
		"The Yearning",
		"Who Yields Not To Despair",
		"Who Dries the Tears of the World",
		"The Limerent Saint",
		"Who Reigns in Compassion",
	],
	look: [
		"A heavy crown like a golden sun, its rays fashioned into reaching hands",
		"Elaborate braids, adorned with flower buds on the verge of blossoming",
		"Hair loose and free, never tangled or grimy, held from the face by a golden circlet",
		"A translucent veil that glitters like the dawn",
		"Eyes hidden behind a swarm of golden-winged butterflies",
		"Honey-colored eyes, always misty with compassion",
		"Tear-streaked cheeks, glimmering like morning dew",
		"A betrothal necklace, tight like a noose",
		"A soft, round face, cheeks still remembering how to blush",
		"Ribcage cracked open, exposing your beating heart for all",
		"Delicate scars like lace patterns on wrists",
		"Hands without gloves, unmarred by labor or violence",
		"Porcelain skin, faint light glows through the cracks",
		"A blood-stained leather armbrace, too big around the wrist",
		"A cerulean silk journade embroidered with dragonflies over a white kirtle",
		"A white and gold doublet, shoulders stained from embracing the weeping",
		"A fine muslin chemise with embroidery detailing, see-through and delicate",
		"Calves wrapped in dozens of fluttering butterfly wings, delicately pinned together",
		"Soft leather poulaines, not made for walking",
		"Bare feet, so light they leave no imprints in the soil",
	],
	rituals: [
		"The Heart Murmurs",
		"The Gentle Breaking",
		"The Regaling of Tales",
		"Love’s Inspiration",
		"The Purifying Embrace",
	],
	questions: [
		"Did you test or demand your Champion’s loyalty?",
		"Did you show vulnerability or compassion at a cost?",
		"Did you encourage someone to do something reckless or dangerous in the name of hope?",
		"Did you give an impassioned monologue about the beauty in the broken things?",
		"Did you secretly or privately act in a way that goes against your imposed Virtue?",
	],
	abilities: {
		vitality: -1,
		composure: 2,
		reason: 0,
		presence: 2,
		cinder: -2,
	},
	cinders: {
		1: "The Breaking Light — It is in the breaking of souls we create spaces for the light to seep through.",
		2: "The Bleeding Of the Self — Love is not measured in heartbeats, but in sacrifice.",
		3: "The Porcelain Heart — Forgiveness exalts the soul. Surrender purifies it.",
		4: "The Defiant Hope — Violence cannot unmake what hope rebuilds.  ",
		5: "The Spring Eternal — Even the coldest winter yearns for spring. Even the darkest hearts can be mellowed. ",
	},
	relics: [
		{
			title: "The shards of Sorrow’s End",
			text: "The sword of your former champion, sharp as the hand which wields it is devoted. Even broken, it may still strike with the <aspect>sweet violence of true love</aspect>. You carry its shards as a promise that <aspect>death has no dominion over love</aspect> and <aspect>what is broken shall reforge the world</aspect>. It carries within its tarnished, broken steel <aspect>a piece of the Dimning, forgiven for its sins</aspect>. ",
			extraLines: 3,
			type: "relic",
		},
		{
			title: "The Tears of The Pleading",
			text: "A necklace of rows and rows of crystallized tears, big enough to hang around your shoulders like a capelet. Each tear holds <aspect>a sacrifice made in your name</aspect>. Memories that are <aspect>haunted not by failure, but potential</aspect>. Willingly gifted, each one inspires <aspect>a devotion that could topple empires</aspect>. ",
			extraLines: 3,
			type: "relic",
		},
		{
			title: "The Heart Devoted",
			text: "The heirloom of your Court, a beautiful ring of gold with a heart-shaped gem that <aspect>glows with a light that soothes even the deepest sorrows</aspect>.  Lips that have kissed this ring <aspect>may speak no lie in your presence</aspect> lest they be <aspect>unravelled by what cannot be undone</aspect>. ",
			extraLines: 3,
			type: "relic",
		},
	],
	oldFire: [
		"Narrate a flashback to your childhood. What part of yourself did people expect you to sacrifice, and what did they sacrifice in return to keep you innocent?",
		"Narrate the moment you first met your Champion. Name them. What deed of violence did they commit in your name? Did it thrill you, or terrify you?",
		"Narrate the moment you showed kindness to someone who did not deserve or expect it. What did this sacrifice cost you, and how did it change life for the better for everyone else?",
		"Narrate an intimate moment when your Champion expected you to soothe their sorrows. What did you ask in return? How did your relationship change?",
		"Narrate a moment to when the Dimning made people cold-hearted and cruel, and how this sharpened your resolve. What compromise did you make to protect the weak and downtrodden?",
		"Narrate the moment your Champion sacrificed their life for you. Did they lay their life down freely, or did you demand it of them?",
		"Narrate the moment you knew the Dimning had its hold on you. What final sacrifice did you make for the greater good and what collateral damage did you justify?",
	],
	fireToCome: {
		"The Kindling Gate":
			"Ask your Champion to pick a Cinder for you. Cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate.",
		"The Tinder Arch":
			"Your fallen Champion returns, wishing to reclaim you and end your search for the Hidden Throne. They will be an ongoing Danger in the campaign.",
		"The Hearth's Fuel":
			"Narrate how people are abandoning their everyday lives to perform great, violent deeds in your name. What comforts do they dream you will reward them?",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1. ",
		"The Pyre's Crown":
			"Narrate the moment you turn from the company and walk toward the Throne at the heart of the Old Capital. Ask your Champion if they will ascend with you, or if they stay behind. Then, at the end of this play session, read Ascend the Throne.",
	},
	ascendTheThrone: {
		"If your Champion is with you": [
			"The Old Capital is a broken thing, a ruin of time. Rusted gates weep gently in the wind; towers reach like longing hands to the sky; the very roads are cobblestones so loose it may as well be gravel.",
			"There is a hurt here at the heart of the Old Capital and you have come to soothe it. Against your gentle nature, there is no defense. Stone becomes soft as fresh soil, iron bends like wood. Even the Dimning must yield. ",
			"The Hidden Throne stands empty, yearning to feel warmth again, to be burdened with the weight of love. ",
			"The people that have followed you fall to their knees and start weeping. Their wailing reaches the sky until it shivers. A last, final mourning. A last, final undoing. Love shall unmake what violence could not touch. ",
			"You open your arms to the Dimning. A final embrace of a world that will be no more. ",
			"<strong>Narrate what happens should you embrace and forgive the Dimning.</strong> ",
			"<strong>Ask your Champion:</strong> How do you break me? Do you find exaltation in this divine purpose, or do you yearn only for the freedom my death will bring? How does your devotion, perfect or imperfect, reshape the world? ",
			"<strong>Then, describe what happens as you become the beating heart of the universe.</strong> ",
			"Does your tenderness inspire and instill kindness in the rotten hearts of the world, or do you make the world so fragile it shatters completely? Does your love exalt the people, inspiring them to greatness, or does your worship come at the cost of all else? ",
		],
		"If you go alone": [
			"You stumble along pathways with air sorrow stale, your eyes blinded with grief. You have already failed, yet you must persist. You are alone, alone even when followed by many.  ",
			"The Hidden Throne is as hollow and empty as you are. You are so fragile, a wisp of hopeless love confined by skin and bone. You take your rightful place with a sigh that sounds like a last breath. ",
			"Your Champion has abandoned you, so instead you reach a hand for one much lowlier than they. A follower, meek and desperate, leans in the press a delicate kiss to your knuckles. They come away with a broken finger in their hand. Another follower approaches, brushing a hand through your hair as it tears like silk. Every sweet kiss, every gentle caress breaks you further, until the Dimning can slip in. ",
			"Your final breaking has begun. Your final sacrifice. You open your arms. ",
			"<strong>Narrate what happens should you embrace the Dimning.</strong> ",
			"Do you forgive your Champion’s betrayal, or will you make sure that this new world is so utterly devoted to you it will abandon all other pursuits? Are these tears you weep the purifying cleanse the world needs, or does your sorrow unravel the world? ",
		],
	},
	moves: [
		{
			title: "…Let My Love Be Thine Weapon…",
			text: [
				"When confronted with violence, you may invoke your gentle nature to replace an asked Light/Dark Move. Instead, roll with Presence. On a hit, pick from the list and one from the complications list. On a 10+ pick two and one from the complications list. On a 12+, as above, but pick no complication.",
				"<li>You charm the aggressors. Not even the angriest, most violent souls would hurt something as pure as you. No harm is done to you in this movement or scene.</li>",
				"<li>You perceive a weakness or vulnerability. Tell the Keeper what it is. Pick yourself or another Ember to take advantage on a next roll that leverages said weakness or vulnerability.</li>",
				"<li>Violence is but a broken heart lashing out. You see what this violence tries to hide. Tell the Keeper what it is; this will function as a Clue. It cannot conclusively answer the Question.</li>",
				"<li>You were never vulnerable at all, merely acting as bait to set up your Champion. Your Champion may add your Presence score to their next roll, no max.</li>",
				"<li>The story of your divine grace will spread. You will befriend a Side Character as soon as it makes sense to do so in the story, at the Keeper’s discretion.</li>",

				"<strong>Complications:</strong>",
				"<li>A Side Character becomes obsessed with you and will go through extreme and dangerous lengths to get your attention. Take the Condition: Object of [Side Character’s] Affection.</li>",
				"<li>Someone else takes the brunt of the aggression in your place, willingly or not.</li>",
				"<li>There is an unwanted complication from your inaction. </li>",
				"On a miss, you are alone and defenseless in the face of overwhelming violence. Not even your Champion can get to you in time or assist you in any way. This move can’t be used again until after you Make Camp, and prepare for the worst right now.",
			],
		},
		{
			title: "…My Kindness Thine Shield…",
			text: [
				"<strong>When a Side Character or Supplicant witnesses you sacrifice yourself for them, adhere to your Virtue at a personal cost or when the Keeper instructs you to do so,</strong> add their name below. They are now a part of your Flock. As long as they are part of your Flock, any rolls associated with actions they help you with are taken at advantage.",
				"If you erase their name from the list, they will do one of the following:",
				"<li>Protect you in a Struggle or other violent situation, at the cost of their own lives. When called upon to roll, instead describe how they sacrifice themselves for you.</li>",
				"<li>Provide you with a Clue for an ongoing mystery. Tell the Keeper what it is. It cannot conclusively answer a Question by itself.</li>",
				"<li>Provide you with a safe space to Make Camp. Only you need to say what can go wrong, and the roll is made with advantage. </li>",
				"<li>Allow you to make contact with a Servant of the Lord. This meeting will start peacefully, but will not necessarily remain so. You must attend this meeting alone.</li>",
				"<li>Provide you with materials or aid to fix equipment or Relics. Unmark an Aspect.</li>",
				"You may add them to your Flock again following the above procedure.",
			],
			extraLines: 3,
		},
		{
			title: "…I Give All My Heart and Soul…",
			text: [
				"You bring comfort even to the most weary, warmth to the coldest hearts. When you Make Camp, you may ask another to confide their hopes and dreams to you, or open up to you about something they regret. If they do, you may advise or console them. You may both clear all emotional or psychological Conditions, or take the Condition <strong>Hopeful</strong>. You may clear the condition at any time to gain advantage on a next roll.",
			],
		},
		{
			title: "…For a Brighter Future, Ours to Share",
			text: [
				"You do not merely believe in the potential of others, you create it. Your hope shapes the future, blossoming new fates into being. When you <strong>attune yourself to the heartbeat of another Ember</strong>, you can listen to the melody of the future. Roll with Cinder. ",

				"On a hit ask the Keeper: 'What will hurt this Ember?' The Keeper will tell you honestly, but not necessarily completely. If this Ember is your Champion, you may say 'It’s worse than that…'",
				"On a 10+ you may counter. 'Yes, this may be so, unless -' Advise the Ember on a course of action that shows true vulnerability, or is in accordance with one of your Cinders. If the Ember follows your advice, they act with Advantage. On a 12+ this vision of the future will also reveal a Clue. ",
				"On a miss, all you can see is the terrible fate that awaits the other Ember, and the inevitable tragedy of their ways that will lead them there. Hold 1. Just before they roll for a move, you may spend the hold to say 'Your heart sang to me your tragic end.' Describe how their quest for the Hidden Throne fails or ends. They then choose to back down or go through with it. If they go through with it, they mark a box on their XP track, but the miss result on their move is replaced with, 'Your character is immediately retired. The Hallowed Heart will describe how.'",
			],
		},
	],
};
