import type { PlaybookBase } from "../types";

export const HowlingTroubadour: PlaybookBase = {
	title: "The Howling Troubadour",
	intro: [
		"In the Age of Plenty, when the twin moons shone over courts glutted with intrigue, the Troubadours were more than entertainers–they were conduits. Their verses carried stories of love, temptation, rumours, and lies. A single stanza could unmake a monarch, a whispered refrain could draw the dead from their rest. In their greatest revels, their ecstatic howls of pleasure rose as an offering to the Wolf-King himself. ",
		"You were the last of this Howling Choir. You remember palaces drowning in velvet and candlelight, where every poem was a duel and every performance a seduction. ",
		"When the Dimning fell even your verses went silent. Now you have risen as an Ember. Your voice is frayed, your memories out of tune, but the magic still coils beneath your tongue. Somewhere in the starless sky, the Wolf-King waits, ravenous for the Final Elegy only you can sing. ",
		"If you ascend the Throne of the False King it will not be as a poet or prophet, but as the last instrument of the moons’ hunger. The song you offer the world to come will decide whether it wakes, or sleeps forever. ",
	],
	names: [
		"Marguerite",
		"Elio",
		"Guillarmo",
		"Etienne",
		"Henri",
		"Aalis",
		"Enguerrano",
		"Geoffroi",
		"Mahaut",
		"Lunet",
		"Pietro",
		"Amis",
		"Rolando",
		"Catelino",
		"Adenet",
		"Bastien",
		"Symmonet",
		"Vauquelin",
		"Isabo",
		"Guiscardo",
	],
	honorifics: [
		"Twin-Moons",
		"the Beautiful",
		"of the Wolf",
		"the Thorned Lute",
		"Keeper of Secrets",
		"the Mistress Thief",
		"in Minor Key",
		"the Spy of Symphonies",
		"the Night-Crowned",
		"the Velvet-Tongued",
		"the Star-Unmaker",
		"the Dream-Breaker",
		"of the Hollow Harp",
		"the Shadowed Cantor",
		"the Echo-Haunted",
		"the Story Taker",
		"the Wolf’s Delight",
		"the Pale Hymnist",
		"the Silver Dirge",
	],
	look: [
		"hair shorn close to the scalp, revealing a tattooed sonnet",
		"long waves tied back with a leather thong",
		"hair tucked neatly under a velvet beret",
		"chaperon turban, covered in celestial embroidery",
		"shrewd, analytical eyes, piercing with inquisitiveness",
		"large doe eyes that shine when welling with emotion",
		"cheeks painted with crescent moons, one red and one blue",
		"thin moustache and wispy goatee, waxed to fine points",
		"full pouty lips, chapped from biting",
		"nails painted silver, echoing the Wolf-King’s claws",
		"a silver brooch, featuring a wolf in congress with an eager maiden",
		"wolf pelt mantle, spotless and gleaming under the moonlight",
		"slouchy embroidered robes with a decorative belt hugging the hips",
		"fine silk shirt, lightly dappled with wine stains",
		"brocade doublet, unbuttoned to expose just enough of your chest",
		"tight leather trousers that hug every curve",
		"sensible travelling shoes",
		"ankle bracelets, bells jingling with every step",
		"gaudy golden sandals, stolen from a member of the Sun Queen’s court",
		"riding boots, polished but well-worn",
	],
	rituals: [
		"The Twin-Moon Invocation",
		"Communion of Bodies",
		"Lamenting Unbound",
		"The Song of Secrets",
		"The Story-Taker’s Rite",
	],
	questions: [
		"Did you destroy someone with just your words?",
		"Did you engage in ecstatic or orgiastic worship of the Wolf-King?",
		"Did you perform (publicly or intimately) in a way that shifted the balance of power?",
		"Did you betray your own artistry for the sake of survival?",
		"Did you spill blood instead of using voice, wit, or song?",
	],
	abilities: {
		vitality: 0,
		composure: 1,
		reason: 0,
		presence: 2,
		cinder: -2,
	},
	cinders: {
		1: "The Lyrical Reality - Art changes the world around you.",
		2: "Words Spoken True - Lies can become truth.",
		3: "The Twin-Moon Command - The moons of the Wolf-King are forever watchful.",
		4: "The Physical Melody - Bodies are tools for music and worship.",
		5: "The Dance of Death - A dagger and a word can be equally sharp.",
	},
	relics: [
		{
			title: "The Red Gittern",
			text: "A gittern carved from the wood of an ancient tree and <aspect>stained in the blood of the carver’s murdered spouse</aspect>. Said to be imbued with Fae-magic, when plucked it <aspect>entrances all who listen</aspect>, even <aspect>lulling dangerous beasts into a deep sleep.</aspect>",
			extraLines: 3,
			type: "relic",
		},
		{
			title: "The Wolf King's Coda",
			text: "A silver bladed dagger that <aspect>sings through the air in a crisp, clear note</aspect>. Stories tell that it <aspect>never fails to find its mark deep in the chest of the most dangerous foe</aspect>, even if <aspect>its victim is not the intended one.</aspect>",
			extraLines: 3,
			type: "relic",
		},
		{
			title: "Howling Choirbook",
			text: "A tome bound in the skin of a wolf-slayer that contains the stories and songs from multiple lands. Embellished and dramatic, these tales illustrate <aspect>how the world once was</aspect>, <aspect>how it is now</aspect>, and <aspect>how it could be if the Wolf-King rises again.</aspect>",
			extraLines: 3,
			type: "relic",
		},
	],
	oldFire: [
		"Narrate a flashback to the night under the singular moon when Romulo the Silver-Tongued sang of the Sun Queen’s treachery for all at court to hear.",
		"Narrate a flashback to Romulo’s execution, when his final song ignited the crowd into riot with the fury of Red Rhagar.",
		"Narrate the Howling Choir’s lament bringing Romulo back to life, and the appearance of the new moon, Blue Elcyene.",
		"Narrate a flashback to the Choir traveling the lands after Romulo’s return, spreading their verses, inspiring devotion, and bending hearts toward the Wolf-King.",
		"Narrate a flashback to the night before the final battle between the followers of the Great Wolf and the armies of the Sun Queen, when Romulo encouraged orgiastic worship beneath the moons of the Wolf, blurring devotion and desire.",
		"Narrate a flashback to the morning Romulo led the Howling Choir in song, and made the sun disappear behind the twin moons, allowing the Wolf-King’s army to gain the upper hand.",
		"Narrate a flashback to the Wolf-King’s response in the final battle, and how its hunger reshaped what was once the Sun Queen’s queendom.",
	],
	fireToCome: {
		"The Kindling Gate":
			"Pick a Cinder (do not mark it if it is unmarked) and cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate. ",
		"The Tinder Arch":
			"Tell the Keeper to create a new member of the Court of the Sun Queen, who is a Danger, and mark a box below. The Keeper has a new reaction, Sunlit Vengeance, which causes the Sun Queen courtier to transport you to their Solar Arena whenever you hum, speak poetry, or draw on lunar magic.",
		"The Hearth's Fuel":
			"Elsewhere in the world, the Court of the Sun Queen besmirches the Wolf-King, twisting his legacy into vile acts. Narrate a scene showing someone we have not yet met in the story who believes their lies, and who begins to doubt their own memories of your Choir.",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1. ",
		"The Pyre's Crown":
			"Narrate the moment you turn from the company and walk alone toward the Throne at the heart of the Old Capital. Then, at the end of this play session, read Ascend the Throne.",
	},
	ascendTheThrone: [
		"You stand before the Throne of the False King and sing your final, world-piercing note. The Wolf-King arrives to claim what was always owed.",

		"His shadow pours into your body like a song overtaking a crowded hall. Your voice is the first to transform, with the Wolf-King’s harmony threading through your own. Your spine lifts and your bones tremble like a newly tuned instrument. Your stance lengthens as your body, once tremulous, is taken up by a far greater composer. ",
		"Your spirit, freed in the moment of your possession, hurls skyward. You rise, and cool, and darken until you become a new, third moon. ",
		"<strong>Narrate your rebirth as the Third Moon.</strong> ",
		"What colour moon are you, and what aspects of the Wolf-King do you represent? What eternal song do you sing down from the dark? What hidden parts of the world do you illuminate or distort? What does the Wolf-King do in your old body? ",
		"No matter what follows, you are divided forever: a god stalking the earth, and the moon that both loves and mourns him.",
	],
	moves: [
		{
			title: "…The Song is Truth.",
			text: [
				"Once per session, so long as there are no other Embers in the scene, your prose can make something true. Tell a story in-character, move the marker closer to Red Rhagar, and work with the Keeper to determine what is now true in the world.",
			],
		},
		{
			title: "In a golden voice…",
			text: [
				"You can always de-escalate a non-violent situation with a smile and a song; describe how you do so and move the marker closer to Blue Elcyene. Any future rolls made by you or another Ember that implicate a Side Character that was part of the de-escalation are taken with advantage.",
			],
		},
		{
			title: "…It Giveth…",
			text: [
				"When you use your words to inspire another Ember, strengthening their resolve or calming their fears, move the marker closer to Blue Elcyene, and roll with Cinder.",
				"On a 10+, choose two.",
				"On a 7-9, choose one.",
				"<li>They clear an appropriate Condition.</li>",
				"<li>They take a Condition of your choosing, and gain the following End of Session question so long as they have the Condition: “Did you act in accordance with [Condition]?”, which you get to answer for them. </li>",
				"<li>Their next roll is taken with advantage.</li>",
				"<li>They may unmark an appropriate Aspect.</li>",
			],
		},
		{
			title: "… And it Taketh Away.",
			text: [
				"When you destroy a Side Character physically, spiritually, or socially with your words, describe how it makes you feel, move the marker closer to Red Rhagar, and roll with Presence.",
				"On a 10+, choose two.",
				"On a 7-9, choose one.",
				"<li>Clear any Conditions you wish, including Herald of [Name of Cinder], in which case The Kindling Gate stays marked, but tell the other players they can now mark it on their own sheets.</li>",
				"<li>Your next roll is taken with advantage.</li>",
				"<li>Unmark a single appropriate Aspect.</li>",
				"<li>There are no long-term consequences for your actions.</li>",
			],
		},
	],
};
