import type { PlaybookBase } from "../types";

export const LoneFamisher: PlaybookBase = {
	title: "The Lone Famisher",
	intro: [
		"For many, the Age of Plenty was a time of harmony sought through beauty and enlightenment. You and your tribesmen, however, followed but one principle: ruthlessly consume just as the great beasts of old once did. You were taught to honor your hunger to its fullest expression, and to revel in the pain and devastation that accompanied it. Armed with this credo, you and your brethren sought to take as much from the abundant lands as you could. You were a Famisher, a great and ravenous warlord whose only desire was to gorge on everything the realm had to offer—gold, power, flesh—and leave only ruin behind. You carved jagged paths across the Lands and across your own body, mutilating yourself into a terrific reflection of your cruelty and wantonness—just as all Famishers have done.",

		"The Dimning possessed a dark hunger that eclipsed your own, and it wasn’t long before the bountiful world you once terrorized was swallowed whole by its shadow. For a time the oblivion you were taught to welcome had finally been delivered.",

		"You have been returned to life, though—alone, as a flickering Ember. You wander the Lands Remaining, a desolate husk of a world once ripe for ravaging, now starved for answers. Why have you been the only one of your kind to return, and what bounty will the Throne provide you in these near-barren Lands should you ascend?",
	],
	names: [
		"Dasha",
		"Nyrgal",
		"Grell",
		"Scabba",
		"Thoom",
		"Odus",
		"Jekaal",
		"Ptera",
		"Agath",
		"Kythus",
		"Yrrda",
		"Vreshka",
		"Bhaluk",
		"Lotec",
		"Hyrex",
		"Uriss",
		"Rezek",
		"Murrk",
		"Taloc",
		"Farraz",
	],
	honorifics: [
		"the Red-Jawed",
		"of Hell Clan Grymma",
		"the Ruiner",
		"the God Eater",
		"of the Jagged Paths",
		"the Kingbreaker",
		"the Ashen Doom",
		"the Demi-Beast of Agonis",
		"the Wandering Hate",
		"the Devastator",
		"the Will of Karaka",
		"the Tempest with Teeth",
		"the Render of Flesh and Spirit",
		"the Sunderer",
		"the Woe-Drinker",
		"the Skintaker",
		"the Bloody-Foot Butcher",
		"of the Hungering Storm",
		"who Dances on Bones",
		"the War Hound of Luscarr",
	],
	look: [
		"long matted beard ornamented with coins, bones, and teeth",
		"wild hair painted red, evoking a fiery lion’s mane",
		"a profane sneer, teeth filed to points",
		"iron shrapnel driven into skin, like thorny spines",
		"earlobes stretched with curse-engraved tusks",
		"runic tattoos across the face and arms, inked with piss and ash",
		"crudely amputated nose",
		"bisected tongue, split down the middle",
		"smears of mud, painted to resemble beast markings",
		"mantle made from dried severed hands",
		"a shattered skull, reconfigured into a pauldron",
		"bronze cuirass with a bestial face hammered across the front",
		"a bear trap strapped across the belly, rusted teeth facing outward",
		"stolen rakshasa pelt, its once brilliant coat faded and frayed",
		"belt adorned with plundered fine jewelry, severed ears and fingers still attached",
		"leather straps, woven and braided through cuts in the skin",
		"war banner of a noble army, tattered and refashioned into a loincloth",
		"leather gauntlets, forearms decorated with broken blades",
		"fingers and toes tipped with iron talons, perfect for rending flesh",
		"gladiator-style sandals, with greaves made from leg bones",
	],
	rituals: [
		"Song of Skins",
		"Marrow Reading",
		"The Carving Beot",
		"The Vaunting Roar",
		"Sharpening and Gnashing",
	],
	questions: [
		"Did you savor the taste of flesh and blood from a wanton act of violence?",
		"Did you delight in ruining something beautiful or revered?",
		"Did you proudly boast of your conquests to another?",
		"Did you encounter something that made you question your appetite for destruction?",
		"Did you privately express regret or shame for an act of cruelty?",
	],
	abilities: {
		vitality: 2,
		composure: 0,
		reason: 0,
		presence: 1,
		cinder: -2,
	},
	cinders: [
		"The Pitiless Storm — The quiet and meek crave the thunder of conquest.",
		"Brass and Blood — There is no place for humility in the wild.",
		"Devourance — No appetite shall go unsatisfied.",
		"The Cleaving Edge — Those who will not yield must be cut down.",
		"Despisement — Weakness is a plague, and everything is diseased.",
	],
	relics: [
		{
			title: "The Glutmaw Helm",
			text: "<aspect>A helmet crafted with scraps of rotting leather, scavenged iron, and purloined teeth from beast and man alike.</aspect> The helm is more emblematic than functional, serving as <aspect>a symbol of the Famishers’ irrepressible hunger</aspect> that blinds the wearer to all but <aspect>the object of their fury</aspect>. ",
			extraLines: 2,
		},
		{
			title: "The Thirsting Greataxe",
			text: "Forged using <aspect>bone and jagged steel</aspect>, Famishers were said to hack through prey in a <aspect>blood-drunk frenzy</aspect> when wielding this massive axe. As an old Famisher proverb decrees: <aspect>“a dry blade is a dead blade”</aspect>. ",
			extraLines: 2,
		},
		{
			title: "The Famisher Hunting Horn",
			text: "Famishers preferred bombastic raids over furtive ones, and often signaled their arrival with instruments made from <aspect>the horns of beasts that have long been hunted into extinction</aspect>. It is said the <aspect>inhuman shrieking sound it created could startle <aspect>thunder from the heavens with a single note</aspect>. ",
			extraLines: 2,
		},
	],
	oldFire: [
		"Narrate a flashback to the time of the Old Fire, to your earliest memory of the Famishers. What about them inspired you to follow this path of ravagement?",
		"Narrate a flashback to when you took your Famisher oath, and the blood you shed as part of it? Was it everything you hoped or feared it would be, and what about it still lingers with you?",
		"Narrate a flashback to the time you first encountered the person who would become your Lover. What drew you two together, and why was this affair worth compromising your place in the tribe if uncovered?",
		"Narrate a flashback to the time where you proved yourself worthy of leading the company to Ambarell. What trials did you undergo to earn the respect of your tribesmen, and how was your appointment celebrated?",
		"Narrate a flashback to the last few hours spent with your Lover in secret before setting off for Ambarell. What words of encouragement or warning did they leave you with? How did those words color the start of your campaign the following day?",
		"Narrate a flashback to a time when your company carved its way through unsuspecting villages that bordered the capital city of Ambarell. What signs of the Dimning’s imminent arrival did you disregard in your single-minded pursuit of conquest?",
		"Before you could breach the walls of Ambarell, the Dimning cast its shadow over the Lands and plunged them into uncertainty. What form did it take as it descended upon your company? Did you resist the embrace of its darkness—or welcome it?",
	],
	fireToCome: {
		"The Kindling Gate":
			"Pick a Cinder (do not mark it if it is unmarked) and cross out all others; tell the other Embers they cannot mark The Kindling Gate on their own sheets. Take the Condition: Herald of [Name of Cinder]. Whenever you act in accordance with—or are negatively affected by—the Condition, mark a box below. When all the boxes are marked, you can unmark them to unmark the Cinder. The Herald Condition cannot be cleared in the normal ways, but you can choose to clear it in order to get an automatic 12+ on a roll. If you do this, cross out The Kindling Gate.",
		"The Tinder Arch":
			"The Famishers destroyed entire bloodlines in their merciless raids, but there were those few who survived and carried on in spite of your barbarity. A descendant from one of these survivors has emerged and seeks vengeance. Name this descendant, and tell the Keeper to put them in play as a Danger.",
		"The Hearth's Fuel":
			"The rumbling of a great and terrible storm sends tremors through the skies all across the Lands. In the roar of thunder, you hear whispers from the past. Who is calling out to you, and what do they ask or demand of you as you get ever closer to reaching the Throne. Will you heed them when the time comes to ascend?",
		"The Ashen Passage":
			"Increase Cinder by 1 (max 3) and decrease another ability of your choice by 1.",
		"The Pyre's Crown":
			"Narrate the moment you turn from the company and walk alone toward the Throne at the heart of the Old Capital. Then, at the end of this play session, read Ascend the Throne.",
	},
	ascendTheThrone: [
		"The feeble light of your torch casts its glow within the cavernous throne hall of the Old Capital. The shadow of the Dimning weighs heavy upon you, slowing you to a contemplative pace as your pilgrimage nears its end. Its fantastic appetite mastered your own, and took from you the conquest of Ambarell. Tumorous mounds of obsidian corpses litter this black marble gullet; torch light flickers off their twisted, glassy bodies. You know from their finery that this is the nobility that met their end here, their anguished faces and outstretched hands frozen in an eternal plea for a mercy the Dimning did not afford. As you look upon these dark remains, does a wave of envy wash over you—that you were not the thing to inspire these expressions of terror—or relief that this fate did not befall you?",

		"Finally, you reach it: the Throne. A gilded heart spread open and devoid of life. Your blood races with anticipation. It is waiting for you to claim it.  ",

		"<strong>Narrate what will happen should you ascend the Throne of the Old King.</strong>",

		"Will you grant these dying lands a merciful end by snuffing out the last of its light for good?",

		"Or, will you rebuild them—and if so, will these new Lands be yours to ravage anew, or will you forge a world that has a place for this version of you in it?",
	],
	moves: [
		{
			title: "…for ours is unforgiving…",
			text: [
				"When you take a Hunger Condition, roll with Composure. On a 10+, choose two Boons. On a 7-9, choose one Boon and one Complication.",
				"<h2>Boons:</h2>",
				"<li>Rage ignites every vein, muscle, and tendon. Add 1 to your Vitality (max 4) while you have this Hunger Condition.</li>",
				"<li>You have transcended the haze of bloodlust; you don’t take disadvantage on rolls made with Reason or Composure while you have this Hunger Condition.</li>",
				"<li>The thrill of battle is invigorating; immediately clear all emotional or spiritual Conditions (not the Hunger Condition).</li>",
				"<li>Your gluttony is ceaseless; mark a box on your Hunger track.</li>",
				"<h2>Complications:</h2>",
				"<li>You endanger the nearest Ember; declare what part of them you'd love to eat, and then ask them to give you an appropriate Condition.</li>",
				"<li>You rage attracts unwanted attention; tell the Keeper to immediately put a Danger in play.</li>",
				"<li>Your strength is impressive, but not enough to inspire fear; you do not take advantage on rolls made with Presence while you have this Hunger Condition.</li>",
				"<li>Your appetite is quickly waning; take the Condition: Fatigued.</li>",
				"On a miss, describe your final moments of clarity before you succumb to your berserker nature, then retire this character; tell the Keeper they become an ongoing Danger.",
			],
		},
		{
			title: "…unquenchable…",
			text: [
				"When you take this move, during the next Start of Session, narrate a flashback showing the first time you witnessed the terrible, bloody power of the Red Want, the most sacred artifact of the Famishers. Then, tell the Embers there’s a new Question that can be pursued, and that any Clues gained can be directed to this Question.",
				"Where is the Red Want hidden? (Complexity 4)",
				"Retrieve the Red Want from its hiding place; the Lone Famisher takes it as a new Relic.",
				"The Red Want",
				"This <long blade chiseled from murkstone> and engraved with <runes sacred to the gods of Hunger> is as close to an heirloom as the Famishers possess, and is said to have been <christened with the blood of giants>, whose limbs it could hack through with a single gruesome swing.",
				"When you use the Red Want to butcher a foe you may do one of the following:",
				"Unlock a hidden truth by indulging in the taste of the butchered foe’s flesh; the Keeper will give you a Clue to an active Mystery.",
				"Drink heartily of the warm blood spilled; mark Hunger. ",
				"Claim a body part as a trophy; say what it is and add it as an Aspect to The Red Want.",
			],
		},
		{
			title: "…unstoppable…",
			text: [
				"You can focus on a single Quarry and will not stop until they are felled. If you do so, mark Hunger and tell the other players who (or what) your Quarry is; you may only have one Quarry at a time. You take advantage on any rolls associated with hunting, capturing, and killing the Quarry until it is destroyed or ceases to be a threat (such as resolving a related Mystery). This advantage can be stacked with other effects, giving you up to double advantage (roll four dice and take the two highest).",
			],
		},
		{
			title: "“…and we will forsake all things that do not serve it!”",
			text: [
				"You broke your Famisher oath by taking a secret Lover and entwining your heart with theirs. Though they have been lost to the Dimning, a piece of them remains with you. When you take this move, create the Lover’s Token using the procedure below, and then, during the next Start of Session, narrate a flashback to when your lover gifted it to you.",
				"To create the Lover’s Token, circle one below for each Aspect, and add The Lover’s Token with your chosen Aspects to your Equipment.",
				"<li>Trinket: a simple iron ring, a leather pouch filled with dried flowers, an intricately braided leather cord, a piece of tattooed skin.</li>",
				"<li>Lie: scalping a rival chieftain, disemboweling a general in front of their cavalry, pouring a traveling merchant’s molten jewelry down their own throat, butchering and eating a wayfarer alive.</li>",
				"<li>Memory: the scent of your Lover’s sweat, the caress of your Lover’s fingertips, the taste of your Lover’s scarred lips, your Lover’s grunts of passion. </li>",
				"The Lover’s Token",
				"In the time of the Old Fire, your Lover gifted you a <trinket>. Discretion was necessary, and so you explained to your tribesman it was a trophy, won by <lie>. When you hold it close to you, you instantly recall <memory>. ",
				"When all three Aspects are marked, the Token is destroyed. Narrate a scene showing the destruction of this object. How does the loss of the Lover’s Token forever change you—do you find some new way to commemorate them, or do you finally let them go? Then, mark every unmarked box on Hunger.",
			],
		},
	],
};
